export {router as authRouter} from "./auth"
export {router as userRouter} from "./user"
export {router as postRouter} from "./post"
// export { router as chatRouter } from "./chat"
export { commentRouter } from "./comment"
export * from "./gateway"